// src/app/education/page.tsx
'use client';

/**
 * Education page — equivalent to src/routes/education/+page.svelte + intro.svelte + education.svelte
 * Combined into a single page component for simplicity.
 * The Svelte writable store (createBookCheckout) is replaced with useState + localStorage.
 */

import React, { useState, useEffect, useRef } from 'react';
import Menu from '@/components/common/Menu';
import ScrollDown from '@/components/common/ScrollDown';
import { technology_learned, bookCheckoutStore } from './education';
import styles from './Education.module.scss';

export default function EducationPage() {
  const [touchscreen, setTouchscreen] = useState(false);
  const [bookCheckedOut, setBookCheckedOut] = useState(false);
  const [iconIndex, setIconIndex] = useState(-1);
  const [showScrollIcon, setShowScrollIcon] = useState(true);
  const educationContentRef = useRef<HTMLDivElement>(null);
  const maskRef = useRef<HTMLDivElement>(null);
  const inMaskRef = useRef(false);

  useEffect(() => {
    if ('ontouchstart' in window) setTouchscreen(true);
    bookCheckoutStore.init();
  }, []);

  // ---- Mask gradient effect (education.svelte) ----
  function updateMaskHeight() {
    if (maskRef.current && educationContentRef.current) {
      maskRef.current.style.setProperty(
        '--var-height',
        `${educationContentRef.current.clientHeight}px`
      );
    }
  }

  function moveGradient(e: MouseEvent) {
    const div = e.target as HTMLDivElement;
    const rect = div.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;
    maskRef.current?.style.setProperty('--mouse-x', `${x}px`);
    maskRef.current?.style.setProperty('--mouse-y', `${y}px`);
  }

  function hideGradient() {
    maskRef.current?.style.setProperty('--mouse-x', '200%');
    maskRef.current?.style.setProperty('--mouse-y', '200%');
  }

  function displayIconsDescription(e: MouseEvent) {
    if (!maskRef.current) return;
    maskRef.current.style.pointerEvents = 'none';
    const el = document.elementFromPoint(e.clientX, e.clientY);
    if (el !== null && el.classList.contains('tech')) {
      const n = el.id.split('-');
      setIconIndex(Number(n[n.length - 1]));
    } else {
      setIconIndex(-1);
    }
    maskRef.current.style.pointerEvents = 'auto';
  }

  useEffect(() => {
    updateMaskHeight();

    const handleMouseMove = (e: MouseEvent) => {
      if (maskRef.current && bookCheckoutStore.read() && inMaskRef.current) {
        displayIconsDescription(e);
        moveGradient(e);
      } else if (maskRef.current) {
        hideGradient();
      }
    };

    const handleScroll = () => updateMaskHeight();

    document.addEventListener('mousemove', handleMouseMove);
    document.addEventListener('scroll', handleScroll);

    const mask = maskRef.current;
    const handleMouseLeave = () => { inMaskRef.current = false; };
    const handleMouseEnter = () => {
      inMaskRef.current = true;
      updateMaskHeight();
    };
    mask?.addEventListener('mouseleave', handleMouseLeave);
    mask?.addEventListener('mouseenter', handleMouseEnter);

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => setShowScrollIcon(!entry.isIntersecting));
      },
      { threshold: 0.05 }
    );
    const wrapper = document.querySelector<HTMLElement>('#black-over-top');
    if (wrapper) observer.observe(wrapper);

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('scroll', handleScroll);
      mask?.removeEventListener('mouseleave', handleMouseLeave);
      mask?.removeEventListener('mouseenter', handleMouseEnter);
      observer.disconnect();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ---- Intro — book checkout button (intro.svelte) ----
  function checkedOutBook() {
    const next = bookCheckoutStore.toggle();
    setBookCheckedOut(next);
    const main = document.querySelector<HTMLElement>('#main-div');
    if (main) {
      main.style.cursor = next
        ? 'url("/Education/book-cursor.png") 28 23, auto'
        : 'default';
    }
  }

  return (
    <div id="main-div" className={styles['main-div']}>
      {touchscreen && (
        <div id="touch-screen" className={styles['touch-screen']}>
          <h1>Warning:</h1>
          <p style={{ textAlign: 'center' }}>
            This channel is meant to be viewed on a computer with a mouse. The experience on mobile
            may be dysfunctional so please if possible revisit this channel on a computer.
          </p>
          <button onClick={() => setTouchscreen(false)}>Continue</button>
        </div>
      )}

      <Menu
        songVolumeLevel={0.3}
        songPath="https://files.catbox.moe/p5bsgp.mp3"
        songName="Mozart Symphony 40"
      />

      {/* Intro section (intro.svelte) */}
      <section id="intro-div" className={styles['intro-div']} style={{ height: '100vh' }}>
        <div
          style={{
            height: '100vh',
            backgroundImage: 'linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.99))',
          }}
        >
          <div className={styles['content-div']} style={{ top: '25%', marginBottom: '25%' }}>
            <article className={styles['intro-article']}>
              <div>
                <p className={`${styles['intro-text']} ${styles['intro-p']}`} style={{ marginTop: 0, fontSize: '2.5em' }}>
                  &quot;Education is the movement from darkness to light.&quot; – Allan Bloom
                </p>
                <button className={styles.btn} onClick={checkedOutBook}>
                  {bookCheckedOut ? 'Return Book' : 'Checkout Book'}
                </button>
                <br />
                <br />
              </div>
            </article>
          </div>
        </div>
      </section>

      {/* Education section (education.svelte) */}
      <section id="all-education-content">
        <div id="black-over-top" ref={maskRef} className={styles['black-over-top']} />
        <div ref={educationContentRef} className={styles['education-content']}>
          <article className={styles['education-article']}>
            <div>
              <h3 className={styles.degree}>Bachelors Degree In Cybersecurity</h3>
              <h2 className={styles['edu-h2']}>University of Connecticut</h2>
              <h5 className={styles['edu-h5']}>GPA: 3.77</h5>
              <p className={styles['edu-p']} style={{ margin: '4%' }}>
                Getting my education in Cybersecurity was one of the best decisions I&apos;ve made.
                The subject requires a grasp on all CS subjects for setting a secure enterprise
                system. That is network, OS, hardware, front-end, back-end, and CI/CD security.
                With this knowledge I can both excel in personal projects and in the work field.
              </p>
            </div>
            <img className={styles['institute-img']} src="/Education/UConn.JPG" alt="Statue" />
          </article>

          <article className={styles['education-article']}>
            <img
              className={styles['institute-img']}
              src="https://thesquare.gent/wp-content/uploads/2018/09/large_wIX3ZhzVucOdRFpxCgEU8IA_XviqoYYqm6sjdvaS0dM.jpeg"
              alt="Statue"
            />
            <div>
              <h3 className={styles.degree}>Self Taught Expert</h3>
              <h2 className={styles['edu-h2']}>The Internet</h2>
              <h5 className={styles['edu-h5']}>
                Googling Precision and Accuracy (GPA): 99/100
              </h5>
              <p className={styles['edu-p']} style={{ margin: '4%' }}>
                My degree is simply a preamble to all the learning it&apos;ll continue to do for the
                rest of my life. Constantly self-teaching by finding projects to act as vehicles to
                drive my motivation through rough patches of complicated technologies.
              </p>
              <div style={{ display: 'flex', height: 'auto', flexWrap: 'wrap' }}>
                {technology_learned.map((icon, index) => (
                  <div
                    key={index}
                    id={`holder-${index}`}
                    className={`${styles['image-holder']} tech`}
                  >
                    {index === iconIndex && (
                      <div id={`description-${index}`} className={`${styles['description-holder']} tech`}>
                        <div className={styles.description}>
                          <h3 style={{ fontFamily: "'Times New Roman', Times, serif" }}>
                            {icon.iconName}
                          </h3>
                          <ul style={{ textAlign: 'left', fontFamily: "'Times New Roman', Times, serif" }}>
                            {icon.projects.map((project, pi) => (
                              <li key={pi}>{project}</li>
                            ))}
                          </ul>
                        </div>
                      </div>
                    )}
                    <img
                      id={`tech-icon-${index}`}
                      className="tech"
                      style={{ height: '5vmin', width: '5vmin' }}
                      src={icon.icon}
                      alt="Technology Icon"
                    />
                  </div>
                ))}
              </div>
            </div>
          </article>
        </div>
        {showScrollIcon && <ScrollDown text="Checkout Book and Scroll Down" />}
      </section>
    </div>
  );
}

// src/routes/education/education.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { technology_learned, createBookCheckout } from './education';
  import ScrollDown from '../../common/scroll-down.svelte';

  let mask: HTMLElement | null;
  $: iconIndex = -1;
  $: showScrollIcon = true;
  let bookCheckout = createBookCheckout();
  let education_content: HTMLElement;

  function moveGradient(mask: HTMLElement, pos: MouseEvent) {
    let div = pos.target as HTMLDivElement;
    let rect = div.getBoundingClientRect();
    let x = pos.clientX - rect.left;
    let y = pos.clientY - rect.top;
    mask.style.setProperty('--mouse-x', x + 'px');
    mask.style.setProperty('--mouse-y', y + 'px');
  }

  function hideGradient(mask: HTMLElement) {
    mask.style.setProperty('--mouse-x', '200%');
    mask.style.setProperty('--mouse-y', '200%');
  }

  function displayIconsDescription(mask: HTMLElement, pos: MouseEvent) {
    mask.style.pointerEvents = 'none';

    const hiddenElement = document.elementFromPoint(pos.clientX, pos.clientY);
    if (hiddenElement != null && hiddenElement.classList.contains('tech')) {
      let n = hiddenElement.id.split('-');
      iconIndex = Number(n[n.length - 1]);
    } else {
      iconIndex = -1;
    }

    mask.style.pointerEvents = 'auto';
  }

  function updateMaskHeight() {
    mask?.style.setProperty('--var-height', education_content.clientHeight + 'px');
    return true;
  }

  onMount(() => {
    education_content = document.querySelector('.education-content') as HTMLElement;
    updateMaskHeight();
    mask = document.querySelector('.black-over-top');
    let inMask = false;
    document.addEventListener('mousemove', (pos) => {
      if (mask != null && bookCheckout.read() && inMask) {
        displayIconsDescription(mask, pos);
        moveGradient(mask, pos);
      } else if (mask != null) {
        hideGradient(mask);
      }
    });

    document.addEventListener('scroll', () => {
      updateMaskHeight();
    });

    mask?.addEventListener('mouseleave', (e) => {
      inMask = false;
    });

    mask?.addEventListener('mouseenter', (e) => {
      inMask = true;
      updateMaskHeight();
    });

    updateMaskHeight();

    const projectsWrapper = document.querySelector('#black-over-top') as HTMLElement;
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          showScrollIcon = !entry.isIntersecting;
        });
      },
      { threshold: 0.05 }
    );
    observer.observe(projectsWrapper);
  });
</script>

<section id="all-education-content">
  <div id="black-over-top" class="black-over-top"></div>
  <div class="education-content">
    <article class="education-article">
      <div>
        <h3 class="degree">Bachelors Degree In Cybersecurity</h3>
        <h2 class="institution">University of Connecticut</h2>
        <h5>GPA: 3.77</h5>
        <p style="margin: 4%;">
          Getting my education in Cybersecurity was one of the best decisions I've made. The subject
          requires a grasp on all CS subjects for setting a secure enterprise system. That is
          network, OS, hardware, front-end, back-end, and CI/CD security. With this knowledge I can
          both excel in personal projects and in the work field.
        </p>
      </div>
      <img class="institute-img" src="/Education/UConn.JPG" alt="Statue" />
    </article>
    <article class="education-article">
      <img
        class="institute-img"
        src="https://thesquare.gent/wp-content/uploads/2018/09/large_wIX3ZhzVucOdRFpxCgEU8IA_XviqoYYqm6sjdvaS0dM.jpeg"
        alt="Statue"
      />
      <div>
        <h3 class="degree">Self Taught Expert</h3>
        <h2 class="institution">The Internet</h2>
        <h5>Googling Precision and Accuracy (GPA): 99/100</h5>
        <p style="margin: 4%;">
          My degree is simply a preamble to all the learning it'll continue to do for the rest of my
          life. Constantly self-teaching by finding projects to act as vehicles to drive my
          motivation through rough patches of complicated technologies.
        </p>
        <div style="display: flex; height:auto; flex-wrap:wrap;">
          {#each technology_learned as icon, index (index)}
            <div id={'holder-' + index} class="tech image-holder">
              {#if index == iconIndex && updateMaskHeight()}
                <div id={'description-' + index} class="tech description-holder">
                  <div class="description">
                    <h3 style="font-family: 'Times New Roman', Times, serif;">{icon.iconName}</h3>
                    <ul style="text-align: left; font-family:'Times New Roman', Times, serif">
                      {#each icon.projects as project, i (i)}
                        <li>{project}</li>
                      {/each}
                    </ul>
                  </div>
                </div>
              {/if}
              <img
                id={'tech-icon-' + index}
                class="tech tech-icons"
                style="height: 5vmin; width: 5vmin;"
                src={icon.icon}
                alt="Technology Icon"
              />
            </div>
          {/each}
        </div>
      </div>
    </article>
  </div>
  {#if showScrollIcon}
    <ScrollDown text="Checkout Book and Scroll Down"></ScrollDown>
  {/if}
</section>

<style lang="scss">
  #all-education-content {
    height: auto;
    width: auto;
    text-align: center;
  }
  .black-over-top {
    --mouse-x: 150%;
    --mouse-y: 150%;
    --var-height: 100%;
    background-color: rgb(0, 0, 0);
    position: absolute;
    width: 100vw;
    height: var(--var-height);
    z-index: 2;
    mask-image: radial-gradient(
      circle at var(--mouse-x) var(--mouse-y),
      rgba(255, 255, 255, 0) 2vmax,
      rgb(255, 255, 255) 40vmax
    );
  }

  .degree {
    font-family: 'Dancing Script', cursive;
    font-size: 2em;
    color: white;
  }

  h2,
  p,
  h3,
  h5 {
    color: white;
  }

  .education-content {
    padding-top: 10%;
    padding-bottom: 10%;
    width: 90vw;
    height: auto;
    text-align: center;
    margin-left: 5vw;
    margin-right: 5vw;
    position: absolute;
    z-index: 1;
  }

  .education-article {
    padding-top: 10%;
    text-align: center;
    margin-left: auto;
    margin-right: auto;
  }

  .institute-img {
    max-height: 45vh;
    max-width: 35vw;
    border-style: solid;
    border-color: white;
    border-width: 2px;
    z-index: 10;
  }

  .image-holder {
    z-index: 10;
    padding: 2vmin;
    position: relative;
    display: table;
    caption-side: top; //https://stackoverflow.com/questions/21240814/how-to-position-a-div-vertically-above-another-div-when-in-the-code-the-divs-are
  }

  .description,
  h3 {
    color: black;
  }

  .description {
    z-index: 3;
    position: absolute;
    text-align: center;
    // color: black;
    margin: auto;
    padding-right: 20%;
    opacity: 1;
    height: auto;
    width: auto;
    bottom: 100%;
    // right: 5%;
    background-color: rgb(138, 98, 53);
    border-style: solid;
    border-color: rgb(41, 23, 0);
  }

  article {
    height: auto;
    width: auto;
    display: flex;
  }
</style>
