// src/components/menubar/ContactInfo.tsx
'use client';

/**
 * ContactInfo — equivalent to src/routes/_menubar/contactInfo.svelte
 */

import React from 'react';
import styles from './Popup.module.scss';

export default function ContactInfo() {
  return (
    <div id="contact" className={styles.menuPopup}>
      <h2 className={styles.menuLargeText}>Contact Info</h2>

      <h4 className={styles.menuMedText}>Email:</h4>
      <a href="mailto:ezq.valencia@gmail.com" className={styles.menuMedText}>
        ezq.valencia@gmail.com
      </a>

      <h4 className={styles.menuMedText}>Linkedin:</h4>
      <a className={styles.menuMedText} href="https://www.linkedin.com/in/ezequielvalencia/">
        Ezequiel Valencia
      </a>

      <h4 className={styles.menuMedText}>Github:</h4>
      <a className={styles.menuMedText} href="https://github.com/AvocadoMoon">
        AvocadoMoon
      </a>

      <h4 className={styles.menuMedText}>Resume:</h4>
      <a
        className={styles.menuMedText}
        href="https://docs.google.com/document/d/e/2PACX-1vQXG6xgS-gXDlE0v03SPC5k56cUHKYMERYuDSOsqoyo8cLsFWslB_Rmr0B_Het3GDX4m7YfRlge-lbo/pub"
      >
        Personal Resume
      </a>
    </div>
  );
}

// src/routes/_menubar/contactInfo.svelte





<div id="contact" class="menu-popup">
    <h2 class="menu-large-text">Contact Info</h2>

    <h4 class="menu-med-text">Email:</h4>
    <a href="mailto:ezq.valencia@gmail.com" class="menu-med-text">ezq.valencia@gmail.com</a>

    <h4 class="menu-med-text">Linkedin:</h4>
    <a class="menu-med-text" href="https://www.linkedin.com/in/ezequielvalencia/">Ezequiel Valencia</a
    >

    <h4 class="menu-med-text">Github:</h4>
    <a class="menu-med-text" href="https://github.com/AvocadoMoon">AvocadoMoon</a>

    <h4 class="menu-med-text">Resume:</h4>
    <a class="menu-med-text" href="https://docs.google.com/document/d/e/2PACX-1vQXG6xgS-gXDlE0v03SPC5k56cUHKYMERYuDSOsqoyo8cLsFWslB_Rmr0B_Het3GDX4m7YfRlge-lbo/pub">
    Personal Resume
    </a>
</div>

<style lang="scss">
    $button-horizontal-offset: 2%;
    @use '../homeMenu';
    @import url("https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@300&display=swap");
  
    @font-face{
      src: url("/terminal-font.ttf");
      font-family: 'Terminal Font';
    }

  </style>
