// src/routes/_channels/channels.svelte


<!-- TODO: Add work experience, school education, personal code projects, art projects, and other cool websites -->
<!-- TODO: Make cursor be appropiate when hover buttons -->

<script lang="ts">
  import { onMount } from "svelte";
  import { musicController, musicTime, sfxController } from "../../common/myLocalStorage";
  import { channels } from "./channelObject.js";
  import { ChannelFunctions } from "./channelFunctions";
  import ChannelCube from "./channel-cube.svelte";

  let bgMusic: HTMLAudioElement
  let songElements: HTMLAudioElement[] = []
  let hoverAudio: HTMLAudioElement
  let clickAudio: HTMLAudioElement
  let focusedChannel = -1
  $: windowWidth = 1000

  onMount(() => {
    let video = document.querySelector('video');
    if (video != null){
      video.playbackRate = 0.5;
    }
    for (let i = 0; i < channels.length; i++){
      let s = document.getElementById("music-clip-" + i) as HTMLAudioElement
      songElements.push(s)
    }
    getAudioElements()
    windowWidth = window.innerWidth

    window.addEventListener('resize', () =>{
      windowWidth = window.innerWidth
    })

  })

  function focus(index: number, zIndex: string){
    let node = document.getElementById("channelBox-" + index);
    node ? node.style.zIndex = zIndex: null;
    let menuNode = document.getElementById("menu-bar") as HTMLElement;
    menuNode.style.zIndex = "-20";
  }


  function getAudioElements(){
    bgMusic = document.getElementById("bgm") as HTMLAudioElement
    hoverAudio = document.getElementById("channel-hover-audio") as HTMLAudioElement;
    clickAudio = document.getElementById("channel-click-audio") as HTMLAudioElement;
  }

  function moveChannelToCenter(channelIndex: number){
    let box = document.getElementById("channelBox-" + channelIndex) as HTMLElement;
    const boxRect = box.getBoundingClientRect();

    // Get viewport center
    const centerX = window.innerWidth / 2 + boxRect.width / 4;
    const centerY = window.innerHeight / 2 + boxRect.height / 4;

    // Get the current center of the div
    const boxCenterX = boxRect.left + boxRect.width;
    const boxCenterY = boxRect.top + boxRect.height;

    // Calculate distance to center
    const deltaX = centerX - boxCenterX;
    const deltaY = centerY - boxCenterY;

    // Apply translation
    box.style.transform = `translate(${deltaX}px, ${deltaY}px)`;
  }

  function resetChannelPosition(channelIndex: number){
    let box = document.getElementById("channelBox-" + channelIndex) as HTMLElement;
    box.style.transform = ``
  }

  musicTime.reset();

  
  const channelFunctions = new ChannelFunctions();

  // https://www.w3schools.com/howto/howto_css_zoom_hover.asp
  // https://svelte.dev/repl/2cf17ac3b4ea47a0ade11361c242e068?version=3.29.4

    
</script>


<section id="grid-container">
{#each channels as currentChannel, index}
    <!-- Focus blur background -->
    

    <div 
      on:mousedown={(e) => {
        if (!currentChannel.focused && $musicController){
          getAudioElements()
          channelFunctions.playMusic(index, bgMusic, songElements[index], false);
        }
        if (currentChannel.redirect != '' && focusedChannel != index){
          focusedChannel = index;
          moveChannelToCenter(index)
        }
      }}
      on:mouseenter={(e) => {
        if($sfxController){
          getAudioElements()
          hoverAudio.play()
        }
      }}
    role="tab" aria-controls="tabpanel-{index}" tabindex="{index}" class="channel-container">
      <!-- Image Div -->
      {#if currentChannel.redirect != ''}
        <div
            class={focusedChannel == index ? "big-channel-container": "channel-box"}
            id="channelBox-{index}"
            on:animationstart={(e) => focus(index, "50")}
            on:animationend={(e) => focus(index, "1")}>

            <ChannelCube
            cubeColor={currentChannel.cubeColor}
            cubeColorHover={currentChannel.cubeHoverColor}
            id={index}
            focusedOn={focusedChannel == index} 
            gifImagePath={currentChannel.gifImage}
            frontImagePath={currentChannel.coverImage} 
            description={currentChannel.channelName}></ChannelCube>
            
        </div>
      {:else if windowWidth > 600}
        <div class="channel-box glass" id="channelBox-{index}">
        </div>
      {/if}


      <!-- Button Section -->
    
    {#if focusedChannel == index}
      <div class="channel-bar">
        <h2>Continue to {currentChannel.channelName} Page?</h2>
        <button on:click={(e) => {
          focusedChannel = -1
          resetChannelPosition(index)
          if ($sfxController){
            clickAudio.play()
          }
          if ($musicController){
            channelFunctions.playMusic(index, bgMusic,  songElements[index], true)
          }}
        }
        class="menu-button channel-buttons future-button"
        id="mbutton-{index}">
          Back
        </button>

        <button on:click={(e) => { if ($sfxController){clickAudio.play();}
          channelFunctions.redirect(index)}} 
          class="play-button channel-buttons future-button" 
        id="pbutton-{index}">
          Continue
        </button>
      </div>
    {/if}

    </div>

    <!-- Blurred background when a channel is selected -->
    {#if focusedChannel != -1}
      <div style="height: 100vh; width:100vw; 
      position:absolute; background-color: rgba(255, 255, 255, 0.111);
      backdrop-filter: blur(2px); top:0;left:0;"></div>
    {/if}

    <audio src="{currentChannel.musicClip}" id="music-clip-{index}"></audio>

{/each}
</section>


<style lang="scss">
  @use "channel";  
</style>

// src/components/channels/Channels.tsx
'use client';

/**
 * Channels — equivalent to src/routes/_channels/channels.svelte
 * Renders the channel grid and manages audio / navigation behaviour.
 */

import React, { useEffect, useRef, useState } from 'react';
import { channels } from './channelObject';
import { ChannelFunctions } from './channelFunctions';
import ChannelCube from './ChannelCube';
import { useAppState } from '@/hooks/useAppState';
import styles from './Channels.module.scss';

const channelFunctions = new ChannelFunctions();

export default function Channels() {
  const { sfx, music, resetMusicTime } = useAppState();

  const [focusedChannel, setFocusedChannel] = useState(-1);
  const [windowWidth, setWindowWidth] = useState(1000);

  // Refs to audio elements expected to exist in the DOM
  const songRefs = useRef<(HTMLAudioElement | null)[]>([]);
  const bgmRef = useRef<HTMLAudioElement | null>(null);
  const hoverAudioRef = useRef<HTMLAudioElement | null>(null);
  const clickAudioRef = useRef<HTMLAudioElement | null>(null);

  useEffect(() => {
    // Slow down any video on the page
    const video = document.querySelector('video');
    if (video) video.playbackRate = 0.5;

    // Collect song element refs
    songRefs.current = channels.map((_, i) =>
      document.getElementById(`music-clip-${i}`) as HTMLAudioElement | null,
    );

    getAudioElements();
    setWindowWidth(window.innerWidth);

    const handleResize = () => setWindowWidth(window.innerWidth);
    window.addEventListener('resize', handleResize);

    // Play background music
    bgmRef.current?.play();

    // Reset music playback time on mount
    resetMusicTime();

    return () => window.removeEventListener('resize', handleResize);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function getAudioElements() {
    bgmRef.current = document.getElementById('bgm') as HTMLAudioElement | null;
    hoverAudioRef.current = document.getElementById(
      'channel-hover-audio',
    ) as HTMLAudioElement | null;
    clickAudioRef.current = document.getElementById(
      'channel-click-audio',
    ) as HTMLAudioElement | null;
  }

  function focus(index: number, zIndex: string) {
    const node = document.getElementById(`channelBox-${index}`);
    if (node) node.style.zIndex = zIndex;
    const menuNode = document.getElementById('menu-bar') as HTMLElement | null;
    if (menuNode) menuNode.style.zIndex = '-20';
  }

  function moveChannelToCenter(channelIndex: number) {
    const box = document.getElementById(
      `channelBox-${channelIndex}`,
    ) as HTMLElement | null;
    if (!box) return;
    const boxRect = box.getBoundingClientRect();
    const centerX = window.innerWidth / 2 + boxRect.width / 4;
    const centerY = window.innerHeight / 2 + boxRect.height / 4;
    const boxCenterX = boxRect.left + boxRect.width;
    const boxCenterY = boxRect.top + boxRect.height;
    const deltaX = centerX - boxCenterX;
    const deltaY = centerY - boxCenterY;
    box.style.transform = `translate(${deltaX}px, ${deltaY}px)`;
  }

  function resetChannelPosition(channelIndex: number) {
    const box = document.getElementById(
      `channelBox-${channelIndex}`,
    ) as HTMLElement | null;
    if (box) box.style.transform = '';
  }

  return (
    <section id="grid-container" className={styles.gridContainer}>
      {channels.map((currentChannel, index) => (
        <React.Fragment key={index}>
          <div
            onMouseDown={() => {
              if (
                !currentChannel.focused &&
                music &&
                currentChannel.redirect !== '' &&
                focusedChannel !== index
              ) {
                getAudioElements();
                if (bgmRef.current && songRefs.current[index]) {
                  channelFunctions.playMusic(
                    index,
                    bgmRef.current,
                    songRefs.current[index]!,
                    false,
                  );
                }
              }
              if (currentChannel.redirect !== '' && focusedChannel !== index) {
                setFocusedChannel(index);
                moveChannelToCenter(index);
              }
            }}
            onMouseEnter={() => {
              if (sfx) {
                getAudioElements();
                hoverAudioRef.current?.play();
              }
            }}
            role="tab"
            aria-controls={`tabpanel-${index}`}
            tabIndex={index}
            className={styles.channelContainer}
          >
            {/* Image Div */}
            {currentChannel.redirect !== '' ? (
              <div
                className={
                  focusedChannel === index
                    ? styles.bigChannelContainer
                    : styles.channelBox
                }
                id={`channelBox-${index}`}
                onAnimationStart={() => focus(index, '50')}
                onAnimationEnd={() => focus(index, '1')}
              >
                <ChannelCube
                  cubeColor={currentChannel.cubeColor}
                  cubeColorHover={currentChannel.cubeHoverColor}
                  id={index}
                  focusedOn={focusedChannel === index}
                  gifImagePath={currentChannel.gifImage}
                  frontImagePath={currentChannel.coverImage}
                  description={currentChannel.channelName}
                />
              </div>
            ) : windowWidth > 600 ? (
              <div
                className={`${styles.channelBox} ${styles.glass}`}
                id={`channelBox-${index}`}
              />
            ) : null}

            {/* Button section — shown when a channel is focused */}
            {focusedChannel === index && (
              <div className={styles.channelBar}>
                <h2>Continue to {currentChannel.channelName} Channel?</h2>
                <button
                  onClick={() => {
                    setFocusedChannel(-1);
                    resetChannelPosition(index);
                    if (sfx) clickAudioRef.current?.play();
                    if (music && bgmRef.current && songRefs.current[index]) {
                      channelFunctions.playMusic(
                        index,
                        bgmRef.current,
                        songRefs.current[index]!,
                        true,
                      );
                    }
                  }}
                  className={`${styles.menuButton} ${styles.channelButtons} ${styles.futureButton}`}
                  id={`mbutton-${index}`}
                >
                  Back
                </button>
                <button
                  onClick={() => {
                    if (sfx) clickAudioRef.current?.play();
                    if (music) songRefs.current[index]?.pause();
                    channelFunctions.redirect(index);
                  }}
                  className={`${styles.playButton} ${styles.channelButtons} ${styles.futureButton}`}
                  id={`pbutton-${index}`}
                >
                  Continue
                </button>
              </div>
            )}
          </div>

          {/* Blurred background overlay when any channel is focused */}
          {focusedChannel !== -1 && (
            <div
              style={{
                height: '100vh',
                width: '100vw',
                position: 'absolute',
                backgroundColor: 'rgba(255, 255, 255, 0.111)',
                backdropFilter: 'blur(2px)',
                top: 0,
                left: 0,
              }}
            />
          )}

          {/* Per-channel audio clip */}
          <audio
            src={currentChannel.musicClip}
            id={`music-clip-${index}`}
          />
        </React.Fragment>
      ))}
    </section>
  );
}
