// src/routes/personal_projects/+page.svelte
<script lang="ts">
  import Menu from "../../common/menu.svelte";
  import Dream from "./dream.svelte";
  import Projects from "./projects.svelte";

  import {createTransitionControl, transitionStates} from "./common";

  const transControl = createTransitionControl()
</script>


<div id="main-div">
    <Menu songPath="https://files.catbox.moe/way98y.mp3" email="website@worker.slmail.me" songName="Zora's Domain - Day (Breath of the Wild)"></Menu>
    {#if $transControl === transitionStates.stillInDream}
        <Dream transControl={transControl}></Dream>
    {:else}
        <Projects transControl={transControl}></Projects>
    {/if}
    
    
</div>


<style lang="scss">
    #main-div{
        position: absolute;
        top: 0;
        left: 0;
        height: 100%;
        width: 100%;
        // background-color: #151f2b;
        background-color: black;
        overflow: auto;
    }

</style>

// src/app/personal_projects/page.tsx
'use client';

/**
 * Personal Projects page — equivalent to src/routes/personal_projects/+page.svelte
 * Manages the transition state between Dream intro and Projects display.
 * The Svelte writable store (createTransitionControl) is replaced with useState.
 */

import React, { useState } from 'react';
import Menu from '@/components/common/Menu';
import Dream from './Dream';
import Projects from './Projects';
import styles from './page.module.scss';

const TRANSITION_STATES = {
  stillInDream: 'stillInDream',
  transitionToProjects: 'transitionToProjects',
  showPersonalProjects: 'showPersonalProjects',
} as const;

type TransitionState = (typeof TRANSITION_STATES)[keyof typeof TRANSITION_STATES];

export default function PersonalProjectsPage() {
  const [transitionState, setTransitionState] = useState<TransitionState>(
    TRANSITION_STATES.stillInDream
  );

  const handleTransitionToProjects = () => {
    setTransitionState(TRANSITION_STATES.transitionToProjects);
  };

  const handleSkip = () => {
    setTransitionState(TRANSITION_STATES.showPersonalProjects);
  };

  const handleTransitioned = () => {
    setTransitionState(TRANSITION_STATES.showPersonalProjects);
  };

  return (
    <div id="main-div" className={styles['main-div']}>
      <Menu
        songVolumeLevel={0.3}
        songPath="https://files.catbox.moe/way98y.mp3"
        songName="Zora's Domain - Day (Breath of the Wild)"
      />
      {transitionState === TRANSITION_STATES.stillInDream ? (
        <Dream
          onTransitionToProjects={handleTransitionToProjects}
          onSkip={handleSkip}
        />
      ) : (
        <Projects
          transitionState={transitionState}
          onTransitioned={handleTransitioned}
        />
      )}
    </div>
  );
}
