// src/app/cat_encryption/page.tsx
'use client';

/**
 * Cat Encryption page — equivalent to src/routes/cat_encryption/+page.svelte
 * Matrix background canvas + tabbed Encode/Decode interface.
 */

import React, { useState, useEffect } from 'react';
import Menu from '@/components/common/Menu';
import Tabs from '@/components/common/Tabs';
import Encode from './Encode';
import Decode from './Decode';
import { matrixDisplay } from './matrixBG';
import { importSCSSOptions } from '@/lib/globals';
import styles from './CatEncryption.module.scss';
import './cat-encryption.scss';

const imageOptions = ['Encode Cat', 'Decode Cat'];
const imageOptionsEntries = Object.entries(imageOptions);

export default function CatEncryptionPage() {
  const [activeIndex, setActiveIndex] = useState(0);

  useEffect(() => {
    matrixDisplay();
  }, []);

  return (
    <div id="main-div" className={styles['main-div']}>
      <Menu
        songVolumeLevel={0.3}
        songPath="https://files.catbox.moe/uc8nho.mp3"
        songName="Intense - Only You (Cat Breakdance Section)"
      />

      <div id="title">
        <h1 id="title-text" className={styles.text}>
          Cat Communication
        </h1>
        <p className={styles.text}>
          Hiding your message in cat images using{' '}
          <a style={{ color: 'cadetblue' }} href="https://en.wikipedia.org/wiki/Steganography">
            Stenography
          </a>
          .
        </p>
      </div>

      <canvas id="matrixCanvas" />

      <article id="content">
        <Tabs
          iterable={imageOptionsEntries}
          activeIndex={activeIndex}
          setActiveIndex={setActiveIndex}
          tabSCSSFileLocation={importSCSSOptions.cat_encryption}
          getTabNameFunction={(e) => e[1]}
        />
        {activeIndex === 0 ? <Encode /> : <Decode />}
      </article>
    </div>
  );
}

// src/routes/cat_encryption/+page.svelte
<script lang="ts">
    import Menu from "../../common/menu.svelte";
    import Tabs from "../../common/tabs.svelte";
    import { importSCSSOptions } from "../../globals"
    import Decode from "./decode.svelte"
    import Encode from "./encode.svelte"
    import { onMount } from "svelte"
    import { matrixDisplay } from "./matrixBG"

    onMount(() => {
        matrixDisplay()
    })

    let activeIndex = 0
    const imageOptions = ["Encode Cat", "Decode Cat"]
</script>



<div id="main-div">
    <Menu songVolumeLevel=.3 songPath="https://files.catbox.moe/uc8nho.mp3" songName="Intense - Only You (Cat Breakdance Section)"></Menu>

    <div id="title" style="">
        <h1 id="title-text" class="text">Cat Communication</h1>
        <p class="text">Hiding your message in cat images using <a style="color:cadetblue;" href="https://en.wikipedia.org/wiki/Steganography">Stenography</a>.</p>
    </div>

    <canvas id="matrixCanvas"></canvas>

    <article id="content">
        <Tabs iterable={Object.entries(imageOptions)} bind:activeIndex={activeIndex}
        tabSCSSFileLocation={importSCSSOptions.cat_encryption}
        getTabNameFunction={(e) => {return e[1]}}></Tabs>
        
        
        {#if activeIndex == 0}
            <Encode></Encode>
        {:else}
            <Decode></Decode>
        {/if}
    </article>
</div>


<style lang="scss">

    #main-div{
        top: 0;
        left: 0;
        position: absolute;
        height: auto;
        min-height: 100vh;
        width: 100vw;
        z-index: -100;
        background-color: black;
    }

    #title{
        margin-top: 10vh;
        text-align: center;
    }

    #content{
        width: 100vw;
        height: auto;
    }

    .text{
        color: white;
    }

    #matrixCanvas{
        top: 0;
        left: 0;
        position: absolute;
        height: 100%;
        width: 100vw;
        z-index: -99;
        opacity: .35;
    }

</style>
