// src/routes/work_experience/experience.svelte
<script lang="ts">
  import { experiences } from "./experiences";
  import { musicTime, musicController } from "../../common/myLocalStorage";
  import { onMount } from "svelte";

  onMount(() => {
    const observer = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        if (entry.isIntersecting){
          let n = entry.target.id.split("-");
          let r = "#entry-" + n[n.length - 1];
          let exp: HTMLElement | null = document.querySelector(r);
          exp?.classList.add('in-view')
        }
      })
    })
    let stars = document.querySelectorAll(".star") as NodeListOf<HTMLElement>
    stars.forEach((star) => {
        star.style.top = "" + Math.floor(Math.random() * 100) + "%"
        star.style.left = "" + Math.floor(Math.random() * 100) + "%"
    })
    
    // Get all the elements with the .animate class applied
    const allElementsToAnimate = document.querySelectorAll(".watch")
    allElementsToAnimate.forEach((element) => {observer.observe(element)})

    // Wait until all items are loaded in the DOM, then apply the anchor
    if (window.location.href.includes("#myExperience")){
      var url = location.href;
      url = url.replace("#myExperience", "#myExperience")
      location.href = url
    }

  })


</script>

<section style="" id="wrapper-div">
  {#each {length: 60} as _, i}
    <div style="--fade-time: {Math.max((i * Math.random()) % 5, 2 + Math.random())}s;" class="star"></div>
  {/each}
  <h1 id="world">World</h1>
  <h2 id="myExperience">My Work Experience</h2>
  {#each Object.entries(experiences) as [key, experience], index}
    <div id={"entry-spacer-" + index} class="spacer watch">
      <div
        id={"entry-" + index}
        class={index % 2 == 0 ? "experience-div left": "experience-div right"}
        on:mousedown={(e) => {
          if($musicController){
            musicTime.updateTimeStamp()
          }
          location.href = experience.redirect;
        }}
        aria-controls="tab-index-{index}"
        role="tab"
        tabindex={index}
      >
        <p class="job-time">{experience.time}</p>
        <div class="text-div">
          <h3 class="company-name text">{experience.company}</h3>
          <h5 class="job-title text">{experience.jobTitle}</h5>
          <p class="job-description text">{experience.description}</p>
        </div>
      </div>
    </div>
  {/each}
  <!-- Implemented so that in-view, right, and left class gets compiled -->
  <div class="in-view left right"></div>
</section>

<style lang="scss">
  @import url("https://fonts.googleapis.com/css2?family=Poiret+One&display=swap");
  #wrapper-div {
    margin: 0;
    padding: 0;
    position: absolute;
    background-color: black;
    width: 100vw;
    text-align: center;
    overflow-x: hidden;
  }

  

  #world {
    font-family: "Poiret One", cursive;
    color: white;
    padding-bottom: 50%;
    font-size: 500%;
  }

  h2 {
    color: white;
  }
  .spacer {
    padding: 5%;
  }

  .text-div {
    text-align: center;
    width: 100%;
  }

  .text {
    $margin-percent: 10%;
    color: white;
    margin-left: $margin-percent;
    margin-right: $margin-percent;
  }

  .job-time {
    color: white;
    writing-mode: vertical-lr;
  }

  @keyframes rightToLeft{
    from {
      right: 100%;
      opacity: 0%;
    }
    to {
      right: 0%;
    }
  }

  @keyframes leftToRight{
    from {
      left: 100%;
      opacity: 0%;
    }
    to {
      left: 0%;
    }
  }

  .experience-div {
    margin: auto;
    padding: 2%;
    border-style: dotted;
    border-color: rgb(150, 150, 150);
    width: 80vw;
    display: flex;
    max-width: 1000px;
    right: 100%;
    position: relative;
    background-color: black;
    z-index: 2;
  }

  .in-view.left{
    animation: rightToLeft 2.5s ease;
    animation-iteration-count: 1;
    animation-fill-mode: forwards;
  }

  .in-view.right{
    animation: leftToRight 2.5s ease;
    animation-iteration-count: 1;
    animation-fill-mode: forwards;
  }

  .star{
        --fade-time: 2s;
        width: 0.3em;
        height: 0.3em;
        background-color: white;
        z-index: 1;
        border-radius: 50%;
        position: absolute;
        animation: fadeInAndOut var(--fade-time) infinite alternate;
    }

    @keyframes fadeInAndOut{
        from{
            opacity: 0;
        } to {
            opacity: 1;
        }
    }


</style>

// src/app/work_experience/Experience.tsx
'use client';

/**
 * Experience — equivalent to src/routes/work_experience/experience.svelte
 * IntersectionObserver-driven list of work experiences with slide-in animations.
 */

import React, { useEffect, useRef } from 'react';
import { experiences } from './experiences';
import { useAppState } from '@/hooks/useAppState';
import styles from './Experience.module.scss';
import './experience.scss';

const STAR_COUNT = 60;

export default function Experience() {
  const sectionRef = useRef<HTMLElement>(null);
  const { music, updateTimeStamp } = useAppState();

  useEffect(() => {
    const section = sectionRef.current;
    if (!section) return;

    // Randomise star positions
    const stars = section.querySelectorAll<HTMLElement>(`.${styles.star}`);
    stars.forEach((star) => {
      star.style.top = `${Math.floor(Math.random() * 100)}%`;
      star.style.left = `${Math.floor(Math.random() * 100)}%`;
    });

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          const n = entry.target.id.split('-');
          const targetId = `entry-${n[n.length - 1]}`;
          const exp = section.querySelector<HTMLElement>(`#${targetId}`);
          if (exp) {
            exp.classList.add(styles['in-view']);
          }
        }
      });
    });

    const watchElements = section.querySelectorAll('.watch');
    watchElements.forEach((el) => observer.observe(el));

    // Scroll to #myExperience if the URL includes it
    if (window.location.href.includes('#myExperience')) {
      const url = location.href;
      location.href = url.replace('#myExperience', '#myExperience');
    }

    return () => observer.disconnect();
  }, []);

  const handleExperienceClick = (redirect: string) => {
    if (music) {
      updateTimeStamp(null);
    }
    location.href = redirect;
  };

  return (
    <section ref={sectionRef} id="wrapper-div" className={styles['wrapper-div']}>
      {Array.from({ length: STAR_COUNT }, (_, i) => (
        <div
          key={i}
          className={styles.star}
          style={
            {
              '--fade-time': `${Math.max((i * Math.random()) % 5, 2 + Math.random())}s`,
            } as React.CSSProperties
          }
        />
      ))}

      <h1 id="world" className={styles.world}>
        World
      </h1>
      <h2 id="myExperience">My Work Experience</h2>

      {Object.entries(experiences).map(([key, experience], index) => (
        <div
          key={key}
          id={`entry-spacer-${index}`}
          className={`${styles.spacer} watch`}
        >
          <div
            id={`entry-${index}`}
            className={`${styles['experience-div']} ${
              index % 2 === 0 ? styles.left : styles.right
            }`}
            onMouseDown={() => handleExperienceClick(experience.redirect)}
            aria-controls={`tab-index-${index}`}
            role="tab"
            tabIndex={index}
          >
            <p className={styles['job-time']}>{experience.time}</p>
            <div className={styles['text-div']}>
              <h3 className={`${styles['company-name']} ${styles.text}`}>
                {experience.company}
              </h3>
              <h5 className={`${styles['job-title']} ${styles.text}`}>
                {experience.jobTitle}
              </h5>
              <p className={`${styles['job-description']} ${styles.text}`}>
                {experience.description}
              </p>
            </div>
          </div>
        </div>
      ))}

      {/* Hidden helper — ensures in-view, left, right classes are not tree-shaken */}
      <div className={`${styles['in-view']} ${styles.left} ${styles.right} ${styles['in-view-helper']}`} />
    </section>
  );
}
