// src/routes/zines/displayZine.svelte
<script lang="ts">
  import type { zineMetaData } from './zine';
  export let zine: zineMetaData;
</script>

<div
  style="text-align: center; margin-left:auto; margin-right:auto; padding-top: 7%;
background-image:url('{zine.redirect}/back.jpg');
"
>
  <object class="pdf-object" type="application/pdf" data={zine.pdfPath} aria-label="Zine"> </object>
</div>

<style lang="scss">
  .pdf-object {
    margin-top: 0;
    margin-left: auto;
    margin-right: auto;
    height: 100vh;
    width: 80vw;
  }
</style>

// src/app/zines/DisplayZine.tsx
'use client';

/**
 * DisplayZine — equivalent to src/routes/zines/displayZine.svelte
 * Shows the PDF for a given zine using an <object> tag.
 */

import React from 'react';
import Menu from '@/components/common/Menu';
import type { ZineMetaData } from './zine';

interface DisplayZineProps {
  zine: ZineMetaData;
}

export default function DisplayZine({ zine }: DisplayZineProps) {
  return (
    <div
      style={{
        position: 'absolute',
        top: 0,
        left: 0,
        textAlign: 'center',
        height: '100%',
        width: '100%',
      }}
    >
      <Menu email="" songName="" />
      <div
        style={{
          textAlign: 'center',
          marginLeft: 'auto',
          marginRight: 'auto',
          paddingTop: '7%',
          backgroundImage: `url('${zine.redirect}/back.jpg')`,
        }}
      >
        <object
          style={{
            marginTop: 0,
            marginLeft: 'auto',
            marginRight: 'auto',
            height: '100vh',
            width: '80vw',
          }}
          type="application/pdf"
          data={zine.pdfPath}
          aria-label="Zine"
        />
      </div>
    </div>
  );
}
