// src/app/work_experience/RA/page.tsx
'use client';

/**
 * RA experience page — equivalent to src/routes/work_experience/RA/+page.svelte
 */

import React from 'react';
import Explayout from '../Explayout';
import { experiences } from '../experiences';

export default function RAPage() {
  return (
    <Explayout
      experience={experiences.ra}
      imgSrc="/work_experience/Uconn_logo.png"
      description={[
        `As a residential assistant, I was responsible for the building my residents lived in, spending most of my time with the residents on my floor. While being an RA strenuous situations were encountered frequently. Some situations were potential fire, physical altercations, potential harm to other residents and themselves, property damage, and general college stress-induced problems. All of these problems required both emotional and general intelligence to resolve. In addition to resolving problems, I took time to help inspire residents that were stuck emotionally or intellectually to continue growing.`,
      ]}
      takeaway="Leading in high stress situations, deescalation, and giving life advice to help people in tough times."
    />
  );
}

// src/routes/work_experience/RA/+page.svelte
<script lang="ts">
    import Explayout from "../explayout.svelte";
    import { experiences } from "../experiences";
</script>



<Explayout experience={experiences.ra} 
imgSrc={"/work_experience/Uconn_logo.png"} 
description={[`As a residential assistant, I was responsible for the building my residents lived in, spending most of my time with the residents on my floor. While being an RA strenuous situations were encountered frequently. Some situations were potential fire, physical altercations, potential harm to other residents and themselves, property damage, and general college stress-induced problems. All of these problems required both emotional and general intelligence to resolve. In addition to resolving problems, I took time to help inspire residents that were stuck emotionally or intellectually to continue growing.`,
]} 
takeaway={"Leading in high stress situations, deescalation, and giving life advice to help people in tough times."}>
</Explayout>
