// src/routes/cat_encryption/decode.svelte
<script lang="ts">
    import { getImageData, isAlphaNumeric, StenographyWorkerPayload } from "./common"
    import { decryptMessage, encryptMethod } from "./encryption"
    import StenographyWorker from "./stenography.worker?worker"

    let imageFiles: FileList;
    let isCanvasEmpty = true;
    let isEncrypted = false;
    var file: File;

    let keyFiles: FileList;
    let keyFile: File | null;
    let rawKey: ArrayBuffer;

    var message = ""

    function whenImageLoaded(imageInfo: any){
        const decoderWorker = new StenographyWorker()
        decoderWorker.postMessage(new StenographyWorkerPayload("", imageInfo.data, imageInfo.width, imageInfo.height, false))

        decoderWorker.onmessage = async (e: MessageEvent<StenographyWorkerPayload>) => {
            let decodedMessage = e.data.message;
            if (isEncrypted){
                let cryptoKey = await crypto.subtle.importKey("raw", rawKey, {"name" : encryptMethod},
                                true, ["encrypt", "decrypt"]);
                decodedMessage = await decryptMessage(cryptoKey, decodedMessage);
            }
            message = isAlphaNumeric(decodedMessage) ? decodedMessage : 
            "It seems that either this image has no hidden message, or that the message got corrupted in transit."
        
            isCanvasEmpty = false
        }
        
    }

    function imageFileHasBeenInput(){
        let input = document.getElementById("imageFileInput") as HTMLInputElement
        imageFiles = input.files as FileList;
        file = imageFiles.item(0) as File
        const reader: FileReader = new FileReader()
        reader.readAsDataURL(file)
        reader.onload = async () => {
            let src = reader.result as string

            if(isEncrypted){
                const keyReader: FileReader = new FileReader()
                keyFile = keyFiles.item(0)
                if (keyFile == null){
                    window.alert("A key is required to decode an encrypted message.")
                    return;
                }
                keyReader.readAsArrayBuffer(keyFile)
                keyReader.onload = () =>{
                    rawKey = keyReader.result as ArrayBuffer
                    getImageData(src, whenImageLoaded)
                }
            } else{
                getImageData(src, whenImageLoaded)
            }

        }
    }    

</script>



<div id="decode-div" style="text-align: center;">

    <h3 class="text" style="">
        Input Encoded Image
    </h3>
    
    <form style="text-align: center;">
        <input bind:checked={isEncrypted} id="checkEncrypt" name="checkEncrypt" style="display:inline-block; margin-left:auto; margin-right:auto;" type="checkbox"> 
        <label for="checkEncrypt" class="text" style="margin-left:auto; margin-right:auto; width:fit-content; display:inline-block;">Was the message encrypted as well?</label>
        
        {#if isEncrypted}
            <br>
            <b><label for="keyFileInput" class="text">Key Input: </label></b> 
            <input id="keyFileInput" class="text" style="margin-left: auto; padding-top:3vh; text-align:center;" bind:files={keyFiles} type="file">
        {/if}

        <br>
        <b><label style="" for="keyFileInput" class="text">Cat Input: </label></b> 
        <input id="imageFileInput" class="text" 
        style="margin-left: auto; padding-top:3vh; text-align:center;" 
        bind:files={imageFiles}   type="file" name="file" accept="image/*">

        <br>
        <button style="width: 15vw; min-width:fit-content; height: 4vh; max-height:max-content; margin-left: auto; margin-top:3vh; text-align:center;" on:click={imageFileHasBeenInput}>
            Decode Cat Image</button>
    </form>

    <canvas class={isCanvasEmpty ? "" : "cat-images"} id="decodedImage"></canvas>

    {#if message.length != 0}
    <span style="margin-top:5vh;">
        <br>
        <br>
        <h4 style="display: inline; padding-top:5vh;" class="text">Decoded Message: </h4> 
        <p style="display: inline;" class="text">{message}</p>
        <br>
        <br>
    </span>


    {/if}


</div>


<style lang="scss">
    .text{
        color: white;
    }
    .cat-images{
        margin-top: 5vh;
        aspect-ratio: 1/1;
        border-style:solid;
        border-color: white;
        border-width: 5px;
        height: 40vmin;
        width: 50vmin;

        max-height: 800px;
        max-width: 900px;
    }
</style>

// src/app/cat_encryption/Decode.tsx
'use client';

/**
 * Decode — equivalent to src/routes/cat_encryption/decode.svelte
 * Decodes a hidden message from a cat image via the steganography Web Worker.
 */

import React, { useState, useRef } from 'react';
import { getImageData, isAlphaNumeric, StenographyWorkerPayload } from './common';
import { decryptMessage, encryptMethod } from './encryption';
import styles from './CatEncryption.module.scss';

export default function Decode() {
  const [isCanvasEmpty, setIsCanvasEmpty] = useState(true);
  const [isEncrypted, setIsEncrypted] = useState(false);
  const [message, setMessage] = useState('');

  const keyFilesRef = useRef<FileList | null>(null);
  const rawKeyRef = useRef<ArrayBuffer | null>(null);

  function whenImageLoaded(imageInfo: { data: Uint8ClampedArray; width: number; height: number }) {
    // Next.js-compatible Web Worker instantiation
    const decoderWorker = new Worker(
      new URL('./stenography.worker.ts', import.meta.url)
    );
    decoderWorker.postMessage(
      new StenographyWorkerPayload('', imageInfo.data, imageInfo.width, imageInfo.height, false)
    );

    decoderWorker.onmessage = async (e: MessageEvent<StenographyWorkerPayload>) => {
      let decodedMessage = e.data.message;
      if (isEncrypted && rawKeyRef.current) {
        const cryptoKey = await crypto.subtle.importKey(
          'raw',
          rawKeyRef.current,
          { name: encryptMethod },
          true,
          ['encrypt', 'decrypt']
        );
        decodedMessage = await decryptMessage(cryptoKey, decodedMessage);
      }
      setMessage(
        isAlphaNumeric(decodedMessage)
          ? decodedMessage
          : 'It seems that either this image has no hidden message, or that the message got corrupted in transit.'
      );
      setIsCanvasEmpty(false);
    };
  }

  function imageFileHasBeenInput() {
    const input = document.getElementById('imageFileInput') as HTMLInputElement;
    const imageFiles = input.files as FileList;
    const file = imageFiles.item(0) as File;
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = async () => {
      const src = reader.result as string;
      if (isEncrypted) {
        const keyFile = keyFilesRef.current?.item(0);
        if (keyFile == null) {
          window.alert('A key is required to decode an encrypted message.');
          return;
        }
        const keyReader = new FileReader();
        keyReader.readAsArrayBuffer(keyFile);
        keyReader.onload = () => {
          rawKeyRef.current = keyReader.result as ArrayBuffer;
          getImageData(src, whenImageLoaded);
        };
      } else {
        getImageData(src, whenImageLoaded);
      }
    };
  }

  return (
    <div id="decode-div" style={{ textAlign: 'center' }}>
      <h3 className={styles['decode-text']}>Input Encoded Image</h3>

      <form style={{ textAlign: 'center' }}>
        <input
          checked={isEncrypted}
          onChange={(e) => setIsEncrypted(e.target.checked)}
          id="checkEncrypt"
          name="checkEncrypt"
          style={{ display: 'inline-block', marginLeft: 'auto', marginRight: 'auto' }}
          type="checkbox"
        />
        <label
          htmlFor="checkEncrypt"
          className={styles['decode-text']}
          style={{ marginLeft: 'auto', marginRight: 'auto', width: 'fit-content', display: 'inline-block' }}
        >
          Was the message encrypted as well?
        </label>

        {isEncrypted && (
          <>
            <br />
            <b>
              <label htmlFor="keyFileInput" className={styles['decode-text']}>
                Key Input:{' '}
              </label>
            </b>
            <input
              id="keyFileInput"
              className={styles['decode-text']}
              style={{ marginLeft: 'auto', paddingTop: '3vh', textAlign: 'center' }}
              type="file"
              onChange={(e) => {
                keyFilesRef.current = e.target.files;
              }}
            />
          </>
        )}

        <br />
        <b>
          <label htmlFor="imageFileInput" className={styles['decode-text']}>
            Cat Input:{' '}
          </label>
        </b>
        <input
          id="imageFileInput"
          className={styles['decode-text']}
          style={{ marginLeft: 'auto', paddingTop: '3vh', textAlign: 'center' }}
          type="file"
          name="file"
          accept="image/*"
        />

        <br />
        <button
          type="button"
          style={{
            width: '15vw',
            minWidth: 'fit-content',
            height: '4vh',
            maxHeight: 'max-content',
            marginLeft: 'auto',
            marginTop: '3vh',
            textAlign: 'center',
          }}
          onClick={imageFileHasBeenInput}
        >
          Decode Cat Image
        </button>
      </form>

      <canvas
        className={isCanvasEmpty ? '' : styles['cat-images']}
        id="decodedImage"
      />

      {message.length !== 0 && (
        <span style={{ marginTop: '5vh' }}>
          <br />
          <br />
          <h4 style={{ display: 'inline', paddingTop: '5vh' }} className={styles['decode-text']}>
            Decoded Message:{' '}
          </h4>
          <p style={{ display: 'inline' }} className={styles['decode-text']}>
            {message}
          </p>
          <br />
          <br />
        </span>
      )}
    </div>
  );
}
