// src/routes/menu.svelte
<head>
  <script src="https://kit.fontawesome.com/6a3a94789b.js" crossorigin="anonymous"></script>
</head>
<script lang="ts">
  import { Marquee, Hr } from "flowbite-svelte";
  import { musicController } from "../myLocalStorage";


  let display_entire_menu = false;
  export let email: string;
  export let songName: string;
  export let songPath: string = "";

  let playing = $musicController

</script>

{#if $musicController}
  <audio id="bg-song" volume=0.5 src={songPath} autoplay loop></audio>
  <script lang="ts">
    var audio = document.getElementById("bg-song");
    audio.volume = 0.1;
  </script>
{:else}
  <audio id="bg-song" volume=0.1 src={songPath} loop></audio>
{/if}



<!-- ############ When the menu is not open ################## -->

{#if !display_entire_menu}
<div>
  <nav>
    <button id="menu-nav"
      on:click={(e) => {
        display_entire_menu = !display_entire_menu;
        // scroll = false;
      }}>Menu</button
    >
  </nav>
</div>
{/if}


<!-- #################### Menu is Open ########################### -->

{#if display_entire_menu}
  <div id="home-menu-nav">

    <span class="box" id="music-player" style="width:fit-content; text-align: center; margin-left:auto; margin-right:auto; height:fit-content;">
      <h1 style="color: white; text-align:center; padding:5%; padding-bottom:0%;">Music:</h1>
      <Marquee speed={0.3} hoverSpeed={0.2}>
        <h5>{songName}</h5>
      </Marquee>
      {#if playing}
        <span id="play-button" on:click={(e) => {playing = false}} on:keydown={(e) => {}} role="button" tabindex="0">
          <i style="font-size: x-large;" class="fas fa-pause"></i>
        </span>
      {:else}
        <span id="play-button" on:click={(e) => {playing = true}} on:keydown={(e) => {}} role="button" tabindex="0">
          <i style="font-size: x-large;" class="fas fa-play"></i>
        </span>
      {/if}
      <span id="seeking" style="">
        <span>
          <input id="seeker" type="range" min="1" max="100" value="0">
        </span>
        <span class="text">0:00/2:56</span>
      </span>
      <Hr classHr="my-8" />
    </span>

    <div style="text-align:center;" id="big-button-div">
      <button
        on:click={(e) => {
          location.href = "/";
        }}>Main Menu</button
      >
      <button
        on:click={(e) => {
          display_entire_menu = !display_entire_menu;
        //   scroll = true;
        }}>Return</button
      >
    </div>

    <div id="contact-me">
      <h1>Contact Me</h1>
      <p>Email: {email}</p>
    </div>
  </div>
{/if}

<style lang="scss">
  .text {
    color: white;
  }

  .box {
    border-radius: 5%;
    overflow: auto;
    color: white;
  }

  #home-menu-nav {
    display:grid;
    bottom: 0;
    position: fixed;
    height: 100vh;
    width: 100vw;
    z-index: 999;
    background: rgba(0, 0, 0, 0.85);
  }

  #menu-nav {
    border: none;
    color: white;
    margin: 0;
    padding: 0;
    font-size: 3vmin;
    position: fixed;
    padding: 1vmin;
    left: 50%;
    transform: translate(-50%);
    border-bottom-style: solid;
    border-width: 1px;
    border-color: white;
    z-index: 999;
    background-color: rgba(0, 0, 0, 0.164);
    max-width: 200px;
    max-height: 55px;
    width: 20vmin;
    height: auto;
    text-align: center;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
  }

  #menu-nav:hover {
    text-decoration: underline;
  }

  #big-button-div button {
    background: grey;
    border-radius: 40px;
    height: 10vh;
    width: 20vw;
    margin-left: 5%;
  }

  #contact-me {
    position: relative;
    text-align: center;
    max-height: 20vh;
  }

  #contact-me h1 {
    padding-top: 2vh;
    bottom: 0;
    color: white;
  }

  #contact-me p {
    bottom: 0;
    color: white;
  }

  input[type="range"] {
    appearance: none;
    -webkit-appearance: none;
    background: transparent;
    cursor: pointer;
    width: 15rem;
  }

  
</style>

// src/components/common/Menu.tsx
'use client';

/**
 * Menu — equivalent to src/common/menu.svelte
 * Floating top menu with music player, main menu / return buttons, and contact info.
 * The Flowbite <Marquee> is replaced with a plain CSS marquee using overflow + animation.
 */

import React, { useEffect, useRef, useState } from 'react';
import { useAppState } from '@/hooks/useAppState';
import styles from './Menu.module.scss';
import './menu.scss';

interface MenuProps {
  songName: string;
  songPath?: string;
  songVolumeLevel?: number;
  /** Accepted for API compatibility but not rendered — matches the original menu.svelte behaviour */
  email?: string;
}

function formatAudioTime(t: number): string {
  if (Number.isNaN(t)) return '0:00';
  const mins = Math.floor(t / 60);
  const secs = Math.floor(t % 60);
  return `${mins}:${secs < 10 ? '0' + secs : secs}`;
}

export default function Menu({ songName, songPath = '', songVolumeLevel = 1 }: MenuProps) {
  const { music } = useAppState();

  const audioRef = useRef<HTMLAudioElement>(null);
  const [displayMenu, setDisplayMenu] = useState(false);
  const [paused, setPaused] = useState(!music);
  const [audioLength, setAudioLength] = useState(0);
  const [currentAudioTime, setCurrentAudioTime] = useState(0);

  // Sync play/pause state with the music setting
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;
    audio.volume = songVolumeLevel;
    if (music) {
      audio.play().catch(() => {/* autoplay blocked */});
      setPaused(false);
    } else {
      audio.pause();
      setPaused(true);
    }
  }, [music, songVolumeLevel]);

  // Wire time tracking
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;
    const onTimeUpdate = () => setCurrentAudioTime(audio.currentTime);
    const onDurationChange = () => setAudioLength(audio.duration);
    audio.addEventListener('timeupdate', onTimeUpdate);
    audio.addEventListener('durationchange', onDurationChange);
    return () => {
      audio.removeEventListener('timeupdate', onTimeUpdate);
      audio.removeEventListener('durationchange', onDurationChange);
    };
  }, []);

  // Respond to paused state changes
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;
    if (paused) {
      audio.pause();
    } else {
      audio.play().catch(() => {});
    }
  }, [paused]);

  return (
    <>
      {/* The audio element is always present but only plays based on state */}
      <audio
        ref={audioRef}
        id="bg-song"
        src={songPath}
        loop
        autoPlay={music}
      />

      {/* Collapsed button */}
      {!displayMenu && (
        <div>
          <nav>
            <button
              id="menu-nav"
              className={styles.menuNav}
              onClick={() => setDisplayMenu(true)}
            >
              Menu
            </button>
          </nav>
        </div>
      )}

      {/* Expanded menu */}
      {displayMenu && (
        <div id="home-menu-nav" className={styles.homeMenuNav}>
          {/* Music player */}
          <span
            className={styles.box}
            id="music-player"
            style={{
              width: 'fit-content',
              textAlign: 'center',
              marginLeft: 'auto',
              marginRight: 'auto',
              height: 'fit-content',
            }}
          >
            <h1 style={{ color: 'white', textAlign: 'center', padding: '5%', paddingBottom: 0 }}>
              Music:
            </h1>
            {/* Simple marquee replacement */}
            <div className={styles.marquee}>
              <span>{songName}</span>
            </div>

            <div id="music-nav" className={styles.musicNav}>
              {/* Play / pause */}
              {!paused ? (
                <span
                  id="play-button"
                  className={styles.musicButtons}
                  onClick={() => setPaused(true)}
                  role="button"
                  tabIndex={0}
                  onKeyDown={() => {}}
                >
                  <i style={{ fontSize: 'x-large' }} className="fas fa-pause music-buttons" />
                </span>
              ) : (
                <span
                  id="play-button"
                  className={styles.musicButtons}
                  onClick={() => setPaused(false)}
                  role="button"
                  tabIndex={0}
                  onKeyDown={() => {}}
                >
                  <i style={{ fontSize: 'x-large' }} className="fas fa-play music-buttons" />
                </span>
              )}

              {/* Seeker */}
              <span id="seeking">
                <span>
                  <input
                    id="seeker"
                    type="range"
                    min={1}
                    max={audioLength || 100}
                    value={currentAudioTime}
                    onChange={(e) => {
                      const t = Number(e.currentTarget.value);
                      setCurrentAudioTime(t);
                      if (audioRef.current) audioRef.current.currentTime = t;
                    }}
                  />
                </span>
                <span className={styles.text}>
                  {formatAudioTime(currentAudioTime)}/{formatAudioTime(audioLength)}
                </span>
              </span>
            </div>

            <hr className={styles.divider} />
          </span>

          {/* Navigation buttons */}
          <div style={{ textAlign: 'center' }} id="big-button-div" className={styles.bigButtonDiv}>
            <button onClick={() => { location.href = '/'; }}>Main Menu</button>
            <button onClick={() => setDisplayMenu(false)}>Return</button>
          </div>

          {/* Contact section */}
          <span id="contact-me" className={styles.contactMe}>
            <h1>Contact Me</h1>
            <p>
              Email:{' '}
              <a style={{ color: 'white' }} href="mailto:ezq.valencia@gmail.com">
                ezq.valencia@gmail.com
              </a>{' '}
              | Github:{' '}
              <a style={{ color: 'white' }} href="https://github.com/AvocadoMoon">
                AvocadoMoon
              </a>{' '}
              | Linkedin:{' '}
              <a
                style={{ color: 'white' }}
                href="https://www.linkedin.com/in/ezequielvalencia/"
              >
                Ezequiel Valencia
              </a>{' '}
              | Resume:{' '}
              <a
                style={{ color: 'white' }}
                href="https://docs.google.com/document/d/e/2PACX-1vQXG6xgS-gXDlE0v03SPC5k56cUHKYMERYuDSOsqoyo8cLsFWslB_Rmr0B_Het3GDX4m7YfRlge-lbo/pub"
              >
                Personal Resume
              </a>
            </p>
          </span>
        </div>
      )}
    </>
  );
}
